# Generated by Django 4.0.4 on 2022-05-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('create', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.category')),
            ],
        ),
    ]
